-- MoneyExchangeTHGroup — initial schema for Supabase (Postgres)
-- Run in: Supabase Dashboard → SQL Editor → New query → Paste → Run (once per project).
-- After run: Authentication → Users → Add user; trigger creates public.profiles automatically.

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

-- Links to auth.users (admin users)
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  avatar_url text,
  phone text,
  role text NOT NULL DEFAULT 'admin' CHECK (role = 'admin'),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Must run after public.profiles exists (function body references the table)
CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid()
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_staff() TO anon, authenticated, service_role;

-- Auto-create profile when a user is added in Authentication (matches app/api/admin-users)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    new.id,
    COALESCE(
      new.raw_user_meta_data->>'name',
      split_part(COALESCE(new.email, 'user@local'), '@', 1)
    ),
    COALESCE(new.email, ''),
    'admin'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_new_user();

CREATE TABLE public.articles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  excerpt text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  thumbnail text NOT NULL DEFAULT '',
  article_type text NOT NULL DEFAULT 'บทความ' CHECK (article_type IN ('บทความ', 'ข่าว')),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  author_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE RESTRICT,
  meta_title text,
  meta_description text,
  image_alt_text text,
  focus_keyword text,
  title_en text NOT NULL DEFAULT '',
  excerpt_en text NOT NULL DEFAULT '',
  content_en text NOT NULL DEFAULT '',
  meta_title_en text,
  meta_description_en text,
  image_alt_text_en text,
  title_cn text NOT NULL DEFAULT '',
  excerpt_cn text NOT NULL DEFAULT '',
  content_cn text NOT NULL DEFAULT '',
  meta_title_cn text,
  meta_description_cn text,
  image_alt_text_cn text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_articles_status_created ON public.articles (status, created_at DESC);
CREATE INDEX idx_articles_author ON public.articles (author_id);

CREATE TABLE public.currencies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  flag text NOT NULL DEFAULT '',
  buy_rate double precision NOT NULL,
  sell_rate double precision NOT NULL,
  buy_margin_percent double precision NOT NULL DEFAULT 0,
  sell_margin_percent double precision NOT NULL DEFAULT 0,
  last_updated timestamptz NOT NULL DEFAULT now(),
  sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE public.members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'banned')),
  join_date timestamptz NOT NULL DEFAULT now(),
  wallet_balance double precision NOT NULL DEFAULT 0,
  verified boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_members_email ON public.members (email);
CREATE INDEX idx_members_status ON public.members (status);

CREATE TABLE public.bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  member_id uuid NOT NULL REFERENCES public.members (id) ON DELETE CASCADE,
  member_name text NOT NULL,
  currency_code text NOT NULL,
  currency_flag text NOT NULL DEFAULT '',
  amount double precision NOT NULL,
  rate double precision NOT NULL,
  total_thb double precision NOT NULL,
  pickup_method text NOT NULL CHECK (pickup_method IN ('branch', 'wallet')),
  branch_name text,
  pickup_date timestamptz,
  status text NOT NULL DEFAULT 'pending_payment' CHECK (
    status IN ('pending_payment', 'pending_review', 'approved', 'completed')
  ),
  slip_url text NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_bookings_member ON public.bookings (member_id);
CREATE INDEX idx_bookings_status ON public.bookings (status);

CREATE TABLE public.topup_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  member_id uuid NOT NULL REFERENCES public.members (id) ON DELETE CASCADE,
  member_name text NOT NULL,
  amount double precision NOT NULL,
  transfer_date timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  slip_url text NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_topups_member ON public.topup_requests (member_id);

CREATE TABLE public.exchange_rate_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base_currency text NOT NULL DEFAULT 'THB',
  rates jsonb NOT NULL DEFAULT '{}',
  fetched_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_exchange_cache_base_fetched ON public.exchange_rate_cache (base_currency, fetched_at DESC);

CREATE TABLE public.contact_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  company text,
  message text NOT NULL,
  read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Branch id is client-supplied string (see POST /api/branches)
CREATE TABLE public.branches (
  id text PRIMARY KEY,
  name text NOT NULL,
  name_th text NOT NULL,
  address text NOT NULL DEFAULT '',
  address_th text NOT NULL DEFAULT '',
  address_cn text NOT NULL DEFAULT '',
  hours text NOT NULL DEFAULT '',
  hours_th text NOT NULL DEFAULT '',
  hours_cn text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.branch_currency_margins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id text NOT NULL REFERENCES public.branches (id) ON DELETE CASCADE,
  currency_code text NOT NULL,
  buy_margin_percent double precision NOT NULL DEFAULT 0,
  sell_margin_percent double precision NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (branch_id, currency_code)
);

CREATE INDEX idx_branch_margins_branch ON public.branch_currency_margins (branch_id);

-- ---------------------------------------------------------------------------
-- updated_at on articles
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_articles_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER tr_articles_updated_at
  BEFORE UPDATE ON public.articles
  FOR EACH ROW
  EXECUTE PROCEDURE public.set_articles_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.currencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topup_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exchange_rate_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branch_currency_margins ENABLE ROW LEVEL SECURITY;

-- profiles
CREATE POLICY "profiles_select_own_or_staff"
  ON public.profiles FOR SELECT
  USING (id = auth.uid() OR public.is_staff());

CREATE POLICY "profiles_update_own_or_staff"
  ON public.profiles FOR UPDATE
  USING (id = auth.uid() OR public.is_staff());

CREATE POLICY "profiles_insert_staff"
  ON public.profiles FOR INSERT
  WITH CHECK (public.is_staff());

-- articles: public read published; staff all
CREATE POLICY "articles_select_public_or_staff"
  ON public.articles FOR SELECT
  USING (status = 'published' OR public.is_staff());

CREATE POLICY "articles_insert_staff"
  ON public.articles FOR INSERT
  WITH CHECK (public.is_staff());

CREATE POLICY "articles_update_staff"
  ON public.articles FOR UPDATE
  USING (public.is_staff());

CREATE POLICY "articles_delete_staff"
  ON public.articles FOR DELETE
  USING (public.is_staff());

-- currencies: public read; staff write
CREATE POLICY "currencies_select_all"
  ON public.currencies FOR SELECT
  USING (true);

CREATE POLICY "currencies_insert_staff"
  ON public.currencies FOR INSERT
  WITH CHECK (public.is_staff());

CREATE POLICY "currencies_update_staff"
  ON public.currencies FOR UPDATE
  USING (public.is_staff());

CREATE POLICY "currencies_delete_staff"
  ON public.currencies FOR DELETE
  USING (public.is_staff());

-- members
CREATE POLICY "members_select_staff"
  ON public.members FOR SELECT
  USING (public.is_staff());

CREATE POLICY "members_insert_staff"
  ON public.members FOR INSERT
  WITH CHECK (public.is_staff());

CREATE POLICY "members_update_staff"
  ON public.members FOR UPDATE
  USING (public.is_staff());

CREATE POLICY "members_delete_staff"
  ON public.members FOR DELETE
  USING (public.is_staff());

-- bookings
CREATE POLICY "bookings_all_staff"
  ON public.bookings FOR ALL
  USING (public.is_staff())
  WITH CHECK (public.is_staff());

-- topup_requests
CREATE POLICY "topups_all_staff"
  ON public.topup_requests FOR ALL
  USING (public.is_staff())
  WITH CHECK (public.is_staff());

-- exchange_rate_cache: staff only
CREATE POLICY "exchange_cache_select_staff"
  ON public.exchange_rate_cache FOR SELECT
  USING (public.is_staff());

CREATE POLICY "exchange_cache_insert_staff"
  ON public.exchange_rate_cache FOR INSERT
  WITH CHECK (public.is_staff());

CREATE POLICY "exchange_cache_update_staff"
  ON public.exchange_rate_cache FOR UPDATE
  USING (public.is_staff());

CREATE POLICY "exchange_cache_delete_staff"
  ON public.exchange_rate_cache FOR DELETE
  USING (public.is_staff());

-- contact: anyone can insert; staff read/update
CREATE POLICY "contact_insert_anon"
  ON public.contact_messages FOR INSERT
  WITH CHECK (true);

CREATE POLICY "contact_select_staff"
  ON public.contact_messages FOR SELECT
  USING (public.is_staff());

CREATE POLICY "contact_update_staff"
  ON public.contact_messages FOR UPDATE
  USING (public.is_staff());

-- branches: public read; staff write
CREATE POLICY "branches_select_all"
  ON public.branches FOR SELECT
  USING (true);

CREATE POLICY "branches_insert_staff"
  ON public.branches FOR INSERT
  WITH CHECK (public.is_staff());

CREATE POLICY "branches_update_staff"
  ON public.branches FOR UPDATE
  USING (public.is_staff());

CREATE POLICY "branches_delete_staff"
  ON public.branches FOR DELETE
  USING (public.is_staff());

-- branch_currency_margins: public read (merged in API); staff write
CREATE POLICY "margins_select_all"
  ON public.branch_currency_margins FOR SELECT
  USING (true);

CREATE POLICY "margins_insert_staff"
  ON public.branch_currency_margins FOR INSERT
  WITH CHECK (public.is_staff());

CREATE POLICY "margins_update_staff"
  ON public.branch_currency_margins FOR UPDATE
  USING (public.is_staff());

CREATE POLICY "margins_delete_staff"
  ON public.branch_currency_margins FOR DELETE
  USING (public.is_staff());

-- ---------------------------------------------------------------------------
-- Storage buckets (lib/supabase/storage.ts)
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES
  ('article-images', 'article-images', true, 5242880),
  ('slip-images', 'slip-images', false, 5242880)
ON CONFLICT (id) DO NOTHING;

-- Public read for article images
CREATE POLICY "article_images_public_read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'article-images');

CREATE POLICY "article_images_authenticated_upload"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'article-images'
    AND auth.role() = 'authenticated'
  );

CREATE POLICY "article_images_authenticated_delete"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'article-images'
    AND auth.role() = 'authenticated'
  );

-- Private slips: authenticated read/write (signed URLs + upload)
CREATE POLICY "slip_images_authenticated_select"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'slip-images' AND auth.role() = 'authenticated');

CREATE POLICY "slip_images_authenticated_insert"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'slip-images' AND auth.role() = 'authenticated');

CREATE POLICY "slip_images_authenticated_update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'slip-images' AND auth.role() = 'authenticated');

CREATE POLICY "slip_images_authenticated_delete"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'slip-images' AND auth.role() = 'authenticated');

-- ---------------------------------------------------------------------------
-- Grants (Supabase API roles)
-- ---------------------------------------------------------------------------
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO postgres, anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Optional seed: sample currencies (remove or edit as needed)
-- ---------------------------------------------------------------------------
INSERT INTO public.currencies (code, name, flag, buy_rate, sell_rate, buy_margin_percent, sell_margin_percent, sort_order)
VALUES
  ('USD', 'US Dollar', '🇺🇸', 35.50, 35.80, 0, 0, 1),
  ('EUR', 'Euro', '🇪🇺', 38.20, 38.55, 0, 0, 2),
  ('JPY', 'Japanese Yen (100)', '🇯🇵', 23.10, 23.35, 0, 0, 3)
ON CONFLICT (code) DO NOTHING;

-- ---------------------------------------------------------------------------
-- First admin: Dashboard → Authentication → Users → Add user (email + password).
--   Trigger handle_new_user creates public.profiles automatically.
-- If you ever add a user without the trigger, insert into profiles manually with matching id.
-- Service role in the app bypasses RLS for admin APIs.
--
-- Customer portal (roles customer vs admin, is_staff fix, avatars, policies):
--   run migrations in supabase/migrations/ (e.g. 20260411120000_customer_portal.sql) after this file.
-- ---------------------------------------------------------------------------
