/** Replace `{key}` placeholders in a string */
export function fillTemplate(
  template: string,
  vars: Record<string, string | number>,
): string {
  let s = template;
  for (const [k, v] of Object.entries(vars)) {
    s = s.split(`{${k}}`).join(String(v));
  }
  return s;
}

/** UI copy for admin (TH / EN) — used via useAdminLanguage().screens */

export const screenCopyTh = {
  shared: {
    cancel: "ยกเลิก",
    save: "บันทึก",
    delete: "ลบ",
    loading: "กำลังโหลด...",
    loadingData: "กำลังโหลดข้อมูล...",
    manage: "จัดการ",
    review: "ตรวจสอบ",
    viewDetails: "ดูรายละเอียด",
    viewInfo: "ดูข้อมูล",
    refresh: "รีเฟรช",
    exportCsv: "Export CSV",
    showingOf: "แสดง {shown} จาก {total} รายการ",
    showingMembers: "แสดง {shown} จาก {total} สมาชิก",
    noRows: "ไม่พบรายการ",
    noRowsCategory: "ไม่มีรายการในหมวดนี้",
    allBranches: "ทุกสาขา",
    dash: "—",
  },
  identity: {
    statusAll: "ทั้งหมด",
    statusActive: "ใช้งาน",
    statusSuspended: "ระงับ",
    statusBanned: "แบน",
    unnamed: "ไม่ระบุชื่อ",
    confirmDelete: "ยืนยันลบลูกค้ารายนี้?",
    disabledHintBefore: "",
    disabledHintAfter: "",
    addButton: "+ เพิ่มรายการ",
    addCustomer: "+ เพิ่มลูกค้า",
    searchPh: "ค้นหา...",
    colName: "ชื่อ",
    colMemberId: "รหัสสมาชิก",
    colEmail: "อีเมล",
    colPhone: "เบอร์โทร",
    colStatus: "สถานะ",
    colWallet: "Wallet",
    colDelete: "ลบ",
    optActive: "ใช้งาน",
    optSuspended: "ระงับ",
    optBanned: "แบน",
    modalTitle: "เพิ่มลูกค้า",
    phName: "ชื่อ",
    phEmail: "อีเมล",
    phPhone: "เบอร์โทร",
    colKyc: "KYC",
    colRisk: "ความเสี่ยง",
    btnKyc: "KYC",
  },
  kycMock: {
    banner: "",
    modalTitle: "รายละเอียด KYC",
    sectionIdentity: "ข้อมูลระบุตัวตน",
    sectionAddress: "ที่อยู่",
    sectionRisk: "ความเสี่ยงและการคัดกรอง",
    sectionFunds: "วัตถุประสงค์ / แหล่งที่มาของเงิน",
    sectionDocs: "เอกสาร (placeholder)",
    sectionInternal: "หมายเหตุภายใน",
    legalName: "ชื่อ–สกุลตามบัตร",
    dob: "วันเกิด",
    nationality: "สัญชาติ",
    residence: "ประเทศที่พำนัก",
    idDocType: "ประเภทเอกสาร",
    optNationalId: "บัตรประชาชน",
    optPassport: "หนังสือเดินทาง",
    optOther: "อื่นๆ",
    idNumber: "เลขที่เอกสาร",
    idExpires: "วันหมดอายุเอกสาร",
    kycStatus: "สถานะ KYC",
    address: "ที่อยู่",
    pep: "PEP",
    sanctions: "Sanctions / watchlist",
    sanctionsChecked: "ตรวจล่าสุด",
    sanctionsClear: "ผ่านการคัดกรอง",
    riskTier: "ระดับความเสี่ยง",
    riskLow: "ต่ำ",
    riskMed: "กลาง",
    riskHigh: "สูง",
    riskNote: "หมายเหตุความเสี่ยง",
    servicePurpose: "วัตถุประสงค์ใช้บริการ",
    sof: "แหล่งที่มาของเงิน",
    kycTier: "ระดับ KYC",
    termsConsent: "ยินยอมข้อมูล",
    internalNote: "หมายเหตุพนักงาน",
    docFront: "เอกสารด้านหน้า",
    docBack: "เอกสารด้านหลัง",
    doc_none: "ยังไม่มี",
    doc_pending: "รออัปโหลด",
    doc_uploaded: "อัปโหลดแล้ว",
    lastReview: "ตรวจล่าสุด",
    reviewedBy: "โดย",
    st_draft: "ร่าง",
    st_pending: "รอตรวจ",
    st_approved: "อนุมัติ",
    st_rejected: "ปฏิเสธ",
    st_expired: "หมดอายุ",
    pep_unknown: "ไม่ทราบ",
    pep_yes: "ใช่",
    pep_no: "ไม่ใช่",
    yes: "ใช่",
    no: "ไม่ใช่",
  },
  transactions: {
    disabledHint: "ยังไม่มีข้อมูลธุรกรรม",
    searchPh: "ค้นหาเลขที่ / member id / ชื่อ KYC / สาขา / สกุลเงิน",
    colTime: "วันที่ / เวลา",
    colId: "เลขที่ธุรกรรม",
    colMember: "สมาชิก",
    colMemberName: "ชื่อสมาชิก",
    colMemberId: "รหัสสมาชิก",
    colStatus: "สถานะ",
    colCcy: "CCY",
    colAmount: "จำนวน",
    colRate: "อัตรา (บาท/หน่วย)",
    colThb: "THB",
    colStaff: "พนักงาน",
    colBranch: "สาขา",
    colKyc: "KYC",
    colActions: "การทำงาน",
    linkIdentity: "ลูกค้า",
    mockMemberCount: "สมาชิกในระบบ {count} คน",
    kycTierPrefix: "ระดับ",
    branchUnknown: "—",
    detailTitle: "รายละเอียดธุรกรรม",
    detailBanner: "",
    sectionTxn: "รายการแลกเปลี่ยน",
    sectionMember: "สมาชิกและ KYC",
    memberEmail: "อีเมล",
    memberPhone: "โทรศัพท์",
    memberWallet: "วอลเล็ต",
    memberMissing: "ไม่พบข้อมูลสมาชิกสำหรับรายการนี้",
    linkCustomerProfile: "เปิดหน้าลูกค้า (ค้นหา member นี้)",
    statSumThb: "ยอดรวม THB (ที่กรอง)",
    statTxnCount: "จำนวนรายการ",
    statMembers: "สมาชิก (ไม่ซ้ำ)",
  },
  reports: {
    disabledHint: "ยังไม่มีข้อมูลรายงาน",
    statTxn: "ธุรกรรม (รายการ)",
    statTotal: "ยอดรวม THB",
    statVisit: "Visit รวม (POS)",
    statUniqueMembers: "สมาชิกที่มีธุรกรรม (ไม่ซ้ำ)",
    statAvgTxn: "เฉลี่ยต่อรายการ (THB)",
    sectionDaily: "สรุปรายวัน",
    sectionBranch: "ตามสาขา",
    sectionCurrency: "ตามสกุลเงิน",
    sectionKyc: "สมาชิกตามสถานะ KYC",
    colDate: "วันที่",
    colCount: "จำนวนรายการ",
    colThbSum: "ยอด THB",
    colBranch: "สาขา",
    colVoided: "ยกเลิก (void)",
    sectionBranchIssues: "ปัญหาและเหตุการณ์ตามสาขา",
    colIssueReportedAt: "วันที่บันทึก",
    colIssueReporter: "ผู้ส่ง",
    colIssueSeverity: "ระดับ",
    colIssueSummary: "หัวข้อ",
    colIssueDetail: "รายละเอียด",
    severityLow: "ต่ำ",
    severityMedium: "ปานกลาง",
    severityHigh: "สูง",
    emptyBranchIssues: "ยังไม่มีบันทึกปัญหาตามสาขา — กดบันทึกเพื่อเพิ่ม",
    formToggleRecordIssue: "บันทึกปัญหาสาขา",
    formIssueBranch: "สาขา",
    formIssueSummary: "หัวข้อสั้นๆ",
    formIssueDetail: "รายละเอียด (ถ้ามี)",
    formIssueSeverity: "ระดับความสำคัญ",
    formSubmitIssue: "บันทึก",
    formSubmittingIssue: "กำลังบันทึก...",
    formSuccessIssue: "บันทึกแล้ว",
    formCancelIssue: "ยกเลิก",
    formErrorRequiredIssue: "กรุณาเลือกสาขาและกรอกหัวข้อ",
    colCurrency: "สกุลเงิน",
    colKycStatus: "สถานะ KYC",
    colMemberCount: "จำนวนสมาชิก",
    linkTransactions: "ไปหน้าธุรกรรม",
    exportCsv: "ส่งออกสรุป CSV",
    emptyData: "ยังไม่มีข้อมูลในช่วงนี้",
    scopePill: "ข้อมูลจากระบบ",
    seeAllTransactions: "ดูธุรกรรมทั้งหมด",
    cardHintMock: "อ้างอิงจากธุรกรรมในระบบ",
    chartSectionTitle: "ภาพรวมกราฟ",
    chartDailyThb: "ยอด THB ตามวัน",
    chartCurrencyShare: "สัดส่วนตามสกุลเงิน (ยอด THB)",
    chartBranchThb: "ยอด THB ตามสาขา",
    chartKycMembers: "จำนวนสมาชิกตามสถานะ KYC",
    chartLegendThb: "THB",
    chartLegendCount: "รายการ",
    chartEmpty: "ไม่มีข้อมูลสำหรับกราฟ",
  },
  bookings: {
    pendingReview: "{n} รอตรวจสอบ",
    searchPh: "ค้นหาการจอง...",
    statusAll: "ทั้งหมด",
    statusPendingPay: "รอชำระเงิน",
    statusPendingReview: "รอตรวจสอบ",
    statusApproved: "อนุมัติแล้ว",
    statusCompleted: "สำเร็จ",
    colBookingId: "รหัสจอง",
    colBookedAt: "วันที่จอง",
    colMemberName: "ชื่อสมาชิก",
    colMemberId: "รหัสสมาชิก",
    colCurrency: "สกุลเงิน",
    colAmount: "จำนวน",
    colTotalThb: "ยอดรวม (THB)",
    colChannel: "ช่องทาง",
    colStatus: "สถานะ",
    btnReview: "ตรวจสอบ",
    btnView: "ดูรายละเอียด",
    emptyBookings: "ไม่พบรายการจอง",
    wallet: "Wallet",
  },
  bookingModal: {
    title: "รายละเอียดการจอง",
    statusPendingPay: "รอชำระเงิน",
    statusPendingReview: "รอตรวจสอบ",
    statusApproved: "อนุมัติแล้ว",
    statusCompleted: "ดำเนินการสำเร็จ",
    lblBookingId: "รหัสการจอง",
    lblStatus: "สถานะ",
    lblMember: "ชื่อสมาชิก",
    lblMemberRecordId: "รหัสสมาชิกในฐานข้อมูล",
    lblBookedAt: "วันที่จอง",
    lblCurrency: "สกุลเงิน",
    lblAmount: "จำนวนเงิน",
    lblRate: "อัตราแลกเปลี่ยน",
    lblTotalThb: "ยอดรวม (THB)",
    lblPickup: "ช่องทางรับเงิน",
    walletTransfer: "โอนเข้า Wallet",
    slipPayment: "สลิปการชำระเงิน",
    slipPlaceholder: "(ตัวอย่าง — ยังไม่มีรูปภาพ)",
    qrTitle: "Booking QR Code",
    qrHint: "ลูกค้าใช้แสดง QR นี้ที่สาขาเพื่อรับเงิน",
    note: "หมายเหตุ",
    notePh: "ใส่หมายเหตุ (ถ้ามี)...",
    close: "ปิด",
    advanceFromPayment: "รับชำระเงิน → รอตรวจสอบ",
    approveBooking: "อนุมัติการจอง",
    markComplete: "ดำเนินการสำเร็จ",
  },
  walletPage: {
    colActions: "จัดการ",
    pendingBadge: "{n} รอดำเนินการ",
    filterAll: "ทั้งหมด",
    filterPending: "รอดำเนินการ",
    filterApproved: "อนุมัติแล้ว",
    filterRejected: "ปฏิเสธ",
    statusPending: "รอดำเนินการ",
    statusApproved: "อนุมัติแล้ว",
    statusRejected: "ปฏิเสธ",
    colId: "รหัส",
    colMember: "สมาชิก",
    colAmount: "จำนวนเงิน",
    colTransferDate: "วันที่โอน",
    colStatus: "สถานะ",
    colNote: "หมายเหตุ",
  },
  approvalModal: {
    title: "ตรวจสอบคำขอเติมเงิน",
    reqId: "รหัสคำขอ",
    member: "สมาชิก",
    amount: "จำนวนเงิน",
    transferDate: "วันที่โอน",
    slipTitle: "สลิปการโอนเงิน",
    slipHint: "(ตัวอย่าง — ยังไม่มีรูปภาพ)",
    noteLabel: "หมายเหตุ",
    notePlaceholder: "ใส่หมายเหตุ (ถ้ามี)...",
    approve: "อนุมัติ",
    reject: "ปฏิเสธ",
  },
  membersPage: {
    searchPh: "ค้นหาสมาชิก...",
    filterAll: "ทั้งหมด",
    filterActive: "ใช้งาน",
    filterSuspended: "ระงับ",
    filterBanned: "ถูกแบน",
    statusActive: "ใช้งาน",
    statusSuspended: "ระงับ",
    statusBanned: "ถูกแบน",
    colMember: "สมาชิก",
    colPhone: "เบอร์โทร",
    colStatus: "สถานะ",
    colJoined: "วันที่สมัคร",
    colWallet: "ยอด Wallet",
    emptySearch: "ไม่พบสมาชิกที่ค้นหา",
  },
  memberModal: {
    title: "ข้อมูลสมาชิก",
    statusActive: "ใช้งาน",
    statusSuspended: "ระงับชั่วคราว",
    statusBanned: "ถูกแบน",
    lblFullName: "ชื่อ-นามสกุล",
    lblEmail: "อีเมล",
    lblPhone: "เบอร์โทรศัพท์",
    lblJoined: "วันที่สมัคร",
    lblWallet: "ยอดเงิน Wallet",
    lblVerified: "ยืนยันอีเมล",
    verifiedYes: "ยืนยันแล้ว",
    verifiedNo: "รอยืนยัน",
    editInfo: "แก้ไขข้อมูล",
    suspend: "ระงับบัญชี",
    unsuspend: "ปลดระงับ",
  },
} as const;

export const screenCopyEn = {
  shared: {
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    loading: "Loading...",
    loadingData: "Loading data...",
    manage: "Manage",
    review: "Review",
    viewDetails: "View details",
    viewInfo: "View",
    refresh: "Refresh",
    exportCsv: "Export CSV",
    showingOf: "Showing {shown} of {total}",
    showingMembers: "Showing {shown} of {total} members",
    noRows: "No records found",
    noRowsCategory: "No records in this filter",
    allBranches: "All branches",
    dash: "—",
  },
  identity: {
    statusAll: "All",
    statusActive: "Active",
    statusSuspended: "Suspended",
    statusBanned: "Banned",
    unnamed: "Unnamed",
    confirmDelete: "Are you sure you want to delete this customer?",
    disabledHintBefore: "",
    disabledHintAfter: "",
    addButton: "+ Add record",
    addCustomer: "+ Add customer",
    searchPh: "Search...",
    colName: "Name",
    colMemberId: "Member ID",
    colEmail: "Email",
    colPhone: "Phone",
    colStatus: "Status",
    colWallet: "Wallet",
    colDelete: "Del",
    optActive: "Active",
    optSuspended: "Suspended",
    optBanned: "Banned",
    modalTitle: "Add customer",
    phName: "Name",
    phEmail: "Email",
    phPhone: "Phone",
    colKyc: "KYC",
    colRisk: "Risk",
    btnKyc: "KYC",
  },
  kycMock: {
    banner: "",
    modalTitle: "KYC details",
    sectionIdentity: "Identity",
    sectionAddress: "Address",
    sectionRisk: "Risk and screening",
    sectionFunds: "Purpose / source of funds",
    sectionDocs: "Documents (placeholder)",
    sectionInternal: "Internal note",
    legalName: "Legal name (as on ID)",
    dob: "Date of birth",
    nationality: "Nationality",
    residence: "Country of residence",
    idDocType: "ID document type",
    optNationalId: "National ID",
    optPassport: "Passport",
    optOther: "Other",
    idNumber: "Document no.",
    idExpires: "Document expiry",
    kycStatus: "KYC status",
    address: "Address",
    pep: "PEP",
    sanctions: "Sanctions / watchlist",
    sanctionsChecked: "Last screened",
    sanctionsClear: "Screening clear",
    riskTier: "Risk tier",
    riskLow: "Low",
    riskMed: "Medium",
    riskHigh: "High",
    riskNote: "Risk note",
    servicePurpose: "Service purpose",
    sof: "Source of funds",
    kycTier: "KYC tier",
    termsConsent: "Consent timestamp",
    internalNote: "Staff note",
    docFront: "Front of document",
    docBack: "Back of document",
    doc_none: "None",
    doc_pending: "Pending upload",
    doc_uploaded: "Uploaded",
    lastReview: "Last review",
    reviewedBy: "By",
    st_draft: "Draft",
    st_pending: "Pending review",
    st_approved: "Approved",
    st_rejected: "Rejected",
    st_expired: "Expired",
    pep_unknown: "Unknown",
    pep_yes: "Yes",
    pep_no: "No",
    yes: "Yes",
    no: "No",
  },
  transactions: {
    disabledHint: "No transaction data",
    searchPh: "Search ref / member id / KYC name / branch / currency",
    colTime: "Date & time",
    colId: "Transaction ref",
    colMember: "Member",
    colMemberName: "Member name",
    colMemberId: "Member ID",
    colStatus: "Status",
    colCcy: "CCY",
    colAmount: "Amount",
    colRate: "Rate (THB per unit)",
    colThb: "THB",
    colStaff: "Staff",
    colBranch: "Branch",
    colKyc: "KYC",
    colActions: "Actions",
    linkIdentity: "Customers",
    mockMemberCount: "{count} members",
    kycTierPrefix: "Tier",
    branchUnknown: "—",
    detailTitle: "Transaction details",
    detailBanner: "",
    sectionTxn: "Exchange line",
    sectionMember: "Member & KYC",
    memberEmail: "Email",
    memberPhone: "Phone",
    memberWallet: "Wallet",
    memberMissing: "No member record found for this transaction.",
    linkCustomerProfile: "Open customer list (search this member)",
    statSumThb: "Total THB (filtered)",
    statTxnCount: "Transactions",
    statMembers: "Unique members",
  },
  reports: {
    disabledHint: "No report data",
    statTxn: "Transactions",
    statTotal: "Total THB",
    statVisit: "Total visits (POS)",
    statUniqueMembers: "Unique members (with txns)",
    statAvgTxn: "Avg per transaction (THB)",
    sectionDaily: "Daily summary",
    sectionBranch: "By branch",
    sectionCurrency: "By currency",
    sectionKyc: "Members by KYC status",
    colDate: "Date",
    colCount: "Count",
    colThbSum: "THB total",
    colBranch: "Branch",
    colVoided: "Voided",
    sectionBranchIssues: "Branch issues & incidents",
    colIssueReportedAt: "Recorded",
    colIssueReporter: "Sent by",
    colIssueSeverity: "Level",
    colIssueSummary: "Summary",
    colIssueDetail: "Detail",
    severityLow: "Low",
    severityMedium: "Medium",
    severityHigh: "High",
    emptyBranchIssues: "No branch issues logged yet — use Record to add one.",
    formToggleRecordIssue: "Record branch issue",
    formIssueBranch: "Branch",
    formIssueSummary: "Short summary",
    formIssueDetail: "Detail (optional)",
    formIssueSeverity: "Severity",
    formSubmitIssue: "Save",
    formSubmittingIssue: "Saving...",
    formSuccessIssue: "Saved.",
    formCancelIssue: "Cancel",
    formErrorRequiredIssue: "Choose a branch and enter a summary.",
    colCurrency: "Currency",
    colKycStatus: "KYC status",
    colMemberCount: "Members",
    linkTransactions: "Open transactions",
    exportCsv: "Export summary CSV",
    emptyData: "No data for this summary",
    scopePill: "System data",
    seeAllTransactions: "View all transactions",
    cardHintMock: "From system transactions",
    chartSectionTitle: "Charts",
    chartDailyThb: "THB by day",
    chartCurrencyShare: "Share by currency (THB)",
    chartBranchThb: "THB by branch",
    chartKycMembers: "Members by KYC status",
    chartLegendThb: "THB",
    chartLegendCount: "Txns",
    chartEmpty: "No data to chart",
  },
  bookings: {
    pendingReview: "{n} pending review",
    searchPh: "Search bookings...",
    statusAll: "All",
    statusPendingPay: "Awaiting payment",
    statusPendingReview: "Pending review",
    statusApproved: "Approved",
    statusCompleted: "Done",
    colBookingId: "Booking ID",
    colBookedAt: "Booked at",
    colMemberName: "Member name",
    colMemberId: "Member ID",
    colCurrency: "Currency",
    colAmount: "Amount",
    colTotalThb: "Total (THB)",
    colChannel: "Channel",
    colStatus: "Status",
    btnReview: "Review",
    btnView: "Details",
    emptyBookings: "No bookings found",
    wallet: "Wallet",
  },
  bookingModal: {
    title: "Booking details",
    statusPendingPay: "Awaiting payment",
    statusPendingReview: "Pending review",
    statusApproved: "Approved",
    statusCompleted: "Completed",
    lblBookingId: "Booking ID",
    lblStatus: "Status",
    lblMember: "Member name",
    lblMemberRecordId: "Member record ID",
    lblBookedAt: "Booked at",
    lblCurrency: "Currency",
    lblAmount: "Amount",
    lblRate: "Exchange rate",
    lblTotalThb: "Total (THB)",
    lblPickup: "Pickup / payout",
    walletTransfer: "Wallet transfer",
    slipPayment: "Payment slip",
    slipPlaceholder: "(placeholder — no image yet)",
    qrTitle: "Booking QR Code",
    qrHint: "Customer shows this QR at the branch to receive cash",
    note: "Note",
    notePh: "Add a note (optional)...",
    close: "Close",
    advanceFromPayment: "Payment received → pending review",
    approveBooking: "Approve booking",
    markComplete: "Mark completed",
  },
  walletPage: {
    colActions: "Actions",
    pendingBadge: "{n} pending",
    filterAll: "All",
    filterPending: "Pending",
    filterApproved: "Approved",
    filterRejected: "Rejected",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    colId: "ID",
    colMember: "Member",
    colAmount: "Amount",
    colTransferDate: "Transfer date",
    colStatus: "Status",
    colNote: "Note",
  },
  approvalModal: {
    title: "Review top-up request",
    reqId: "Request ID",
    member: "Member",
    amount: "Amount",
    transferDate: "Transfer date",
    slipTitle: "Transfer slip",
    slipHint: "(placeholder — no image yet)",
    noteLabel: "Note",
    notePlaceholder: "Add a note (optional)...",
    approve: "Approve",
    reject: "Reject",
  },
  membersPage: {
    searchPh: "Search members...",
    filterAll: "All",
    filterActive: "Active",
    filterSuspended: "Suspended",
    filterBanned: "Banned",
    statusActive: "Active",
    statusSuspended: "Suspended",
    statusBanned: "Banned",
    colMember: "Member",
    colPhone: "Phone",
    colStatus: "Status",
    colJoined: "Joined",
    colWallet: "Wallet bal.",
    emptySearch: "No members match your search",
  },
  memberModal: {
    title: "Member details",
    statusActive: "Active",
    statusSuspended: "Suspended",
    statusBanned: "Banned",
    lblFullName: "Full name",
    lblEmail: "Email",
    lblPhone: "Phone",
    lblJoined: "Joined",
    lblWallet: "Wallet balance",
    lblVerified: "Email verified",
    verifiedYes: "Verified",
    verifiedNo: "Pending",
    editInfo: "Edit",
    suspend: "Suspend",
    unsuspend: "Reactivate",
  },
} as const;

export type ScreenCopy = typeof screenCopyTh;
